query getAllOpenPRData {
	viewer {
		login
		repositories(first: 50) {
			nodes {
				id
				name
				url
				pullRequests(states: OPEN, first: 50) {
					nodes {
						id
						url
					}
				}
			}
		}
	}
}
